# Generated by Django 3.1.3 on 2020-12-09 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0002_staffmember_is_approved"),
    ]

    operations = [
        migrations.RemoveField(model_name="staffmember", name="organizer_account",),
        migrations.AddField(
            model_name="staffmember",
            name="organizer",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"role": "organizer"},
                on_delete=django.db.models.deletion.CASCADE,
                to="management.adminaccount",
            ),
            preserve_default=False,
        ),
    ]
