# Generated by Django 3.1.3 on 2020-12-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_auto_20201207_1127"),
        ("events", "0017_delete_staffpass"),
        ("staff", "0003_auto_20201209_1117"),
    ]

    operations = [
        migrations.DeleteModel(name="StaffMember",),
    ]
