# Generated by Django 3.1.3 on 2020-12-09 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_staffmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
