# Generated by Django 3.1.3 on 2020-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0006_auto_20201209_1419"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffinvite",
            name="staff_categories",
            field=models.ManyToManyField(
                related_name="_staffinvite_staff_categories_+", to="staff.StaffCategory"
            ),
        ),
    ]
