# Generated by Django 3.1.3 on 2020-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_staffinvite_staff_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
