# Generated by Django 3.1.3 on 2020-12-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_auto_20201211_1056"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="staff_invite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staffinvite",
            ),
        ),
    ]
