# Generated by Django 3.1.3 on 2020-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_staffpass_was_sent"),
        ("locations", "0007_remove_sublocation_location_owner"),
        ("staff", "0011_auto_20201211_1448"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmember",
            name="current_access_control_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="current_access_control_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="current_access_control_sublocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.sublocation",
            ),
        ),
    ]
