# Generated by Django 3.1.3 on 2020-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_remove_sublocation_location_owner"),
        ("staff", "0012_auto_20201213_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcategory",
            name="available_locations",
            field=models.ManyToManyField(blank=True, to="locations.Location"),
        ),
        migrations.AddField(
            model_name="staffcategory",
            name="available_sublocations",
            field=models.ManyToManyField(blank=True, to="locations.Sublocation"),
        ),
    ]
