# Generated by Django 3.1.3 on 2020-11-12 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "__first__"),
        ("bots", "0001_initial"),
        ("participants", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                (
                    "bot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bots.bot",
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="events", to="locations.Location"
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"role": "organizer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant_categories",
                    models.ManyToManyField(to="participants.ParticipantCategory"),
                ),
            ],
            options={"abstract": False},
        ),
    ]
