# Generated by Django 3.1.3 on 2020-11-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_auto_20201128_1803"),
        ("events", "0003_auto_20201128_1803"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="bot",),
        migrations.AddField(
            model_name="event",
            name="guest_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_events",
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="staff_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_events",
                to="bots.bot",
            ),
        ),
    ]
