# Generated by Django 3.1.3 on 2020-11-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_auto_20201129_2307"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="staff_bot",),
    ]
