# Generated by Django 3.1.3 on 2020-11-30 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_event_staff_bot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="guest_bot", new_name="bot",
        ),
    ]
