# Generated by Django 3.1.3 on 2020-12-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_auto_20201129_1946"),
        ("bots", "0005_auto_20201201_1434"),
        ("participants", "0007_auto_20201129_2253"),
        ("events", "0008_auto_20201130_1734"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="bots.bot",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="locations.Location"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="staff_categories",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="participants.StaffCategory"
            ),
        ),
    ]
