# Generated by Django 3.1.3 on 2020-12-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_auto_20201201_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.FileField(
                blank=True, null=True, upload_to="events/posters/%y/%m/%d"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="telegram_poster_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
