# Generated by Django 3.1.3 on 2020-12-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_auto_20201204_0359"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="poster",),
    ]
