# Generated by Django 3.1.3 on 2020-12-04 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileuploads", "0001_initial"),
        ("events", "0012_remove_event_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fileuploads.fileupload",
            ),
        ),
    ]
