# Generated by Django 3.1.3 on 2020-12-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("events", "0013_event_poster"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="staff_categories"),
    ]
