# Generated by Django 3.1.3 on 2020-12-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("events", "0014_auto_20201208_1123"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="staff_categories",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="staff.StaffCategory"
            ),
        ),
    ]
