# Generated by Django 3.1.3 on 2020-12-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_staffpass"),
    ]

    operations = [
        migrations.DeleteModel(name="StaffPass",),
    ]
