# Generated by Django 3.1.3 on 2020-12-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_staffmember"),
        ("events", "0018_staffpass"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpass",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staff.staffmember"
            ),
        ),
    ]
