# Generated by Django 3.1.3 on 2020-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_staffpass_staff_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffpass",
            name="was_sent",
            field=models.BooleanField(default=False),
        ),
    ]
