# Generated by Django 3.1.3 on 2020-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_staffpass_was_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="selfie_rejected_text",
            field=models.TextField(default="Извините. Будем ждать Вас в другой день."),
        ),
    ]
