# Generated by Django 3.1.3 on 2020-12-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_poster"),
        ("fileuploads", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="FileUpload", new_name="ImageUpload",),
    ]
