# Generated by Django 3.1.3 on 2021-02-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileuploads", "0003_auto_20201204_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageupload",
            name="file",
            field=models.FileField(upload_to="image_uploads/%Y/%m/%d"),
        ),
    ]
