version: "3.7"

services:
  nginx:
    build: ./deployment/nginx

  app:
    build: .

  scheduler:
    build: .

  payment_scheduler:
    build: .

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/srv/src
      - ./frontend/dist:/srv/dist
