# Generated by Django 3.1.3 on 2020-11-22 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="organizers",
            field=models.ManyToManyField(
                limit_choices_to={"role": "organizer"},
                related_name="organizer_locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
