# Generated by Django 3.1.3 on 2020-11-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_auto_20201128_1803"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location", options={"ordering": ("location_owner",)},
        ),
    ]
