# Generated by Django 3.1.3 on 2020-12-16 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_remove_sublocation_location_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sublocation",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sublocations",
                to="locations.location",
            ),
        ),
    ]
