# Generated by Django 3.1.3 on 2020-11-12 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participants", "0001_initial"),
        ("events", "0001_initial"),
        ("locations", "0001_initial"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureConsumption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="features.feature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureLimit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_value", models.IntegerField()),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="features.feature",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("base_price", models.IntegerField()),
                ("max_ticket_count", models.IntegerField()),
                (
                    "available_features",
                    models.ManyToManyField(
                        blank=True,
                        through="tickets.FeatureLimit",
                        to="features.Feature",
                    ),
                ),
                (
                    "available_locations",
                    models.ManyToManyField(blank=True, to="locations.Location"),
                ),
                (
                    "available_sublocations",
                    models.ManyToManyField(blank=True, to="locations.Sublocation"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="TicketPlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TicketPromoCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=500)),
                ("is_disposable", models.BooleanField(default=False)),
                ("new_price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketDiscountByDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("new_price", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_price", models.FloatField()),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketcategory",
                    ),
                ),
                (
                    "consumed_features",
                    models.ManyToManyField(
                        through="tickets.FeatureConsumption", to="features.Feature"
                    ),
                ),
                (
                    "date_discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketdiscountbydate",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="participants.participant",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tickets.ticketpromocode",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="featurelimit",
            name="ticket_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.ticketcategory"
            ),
        ),
        migrations.AddField(
            model_name="featureconsumption",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
            ),
        ),
    ]
