# Generated by Django 3.1.3 on 2020-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_auto_20201122_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategory",
            name="base_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticketcategory",
            name="max_ticket_count",
            field=models.PositiveIntegerField(),
        ),
    ]
