# Generated by Django 3.1.3 on 2020-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_auto_20201201_2255"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
