# Generated by Django 3.1.3 on 2020-12-03 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_auto_20201203_0240"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="with_manual_confirmation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("payed", "Payed"),
                    ("returned", "Returned"),
                ],
                default="created",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseConfirmation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Не обработано"),
                            ("confirmed", "Оплата подтверждена"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_confirmations",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={"ordering": ("-created_at",)},
        ),
    ]
