# Generated by Django 3.1.3 on 2020-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_auto_20201203_0918"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseconfirmation",
            name="image",
            field=models.FileField(upload_to="purchase-confirmations/%Y/%m/%d"),
        ),
    ]
