# Generated by Django 3.1.3 on 2020-12-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_auto_20201203_0928"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcategory",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
