# Generated by Django 3.1.3 on 2020-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_auto_20201203_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="per_participant_limit",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
