# Generated by Django 3.1.3 on 2020-12-07 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0003_auto_20201206_1452"),
        ("tickets", "0011_auto_20201204_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="qrcodes.qrcode",
            ),
        ),
    ]
