# Generated by Django 3.1.3 on 2020-12-07 11:19

import secrets

from django.db import migrations


def create_ticket_qr_codes_if_doesnt_present(apps, schema_editor):
    QrCode = apps.get_model("qrcodes", "QrCode")
    Ticket = apps.get_model("tickets", "Ticket")

    for ticket in Ticket.objects.all():
        if not ticket.qr_code:
            qr_code = QrCode.objects.create(
                type="ticket", token=secrets.token_urlsafe()
            )
            ticket.qr_code = qr_code
            ticket.save(update_fields=("qr_code",))


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_auto_20201207_0338"),
    ]

    operations = [
        migrations.RunPython(create_ticket_qr_codes_if_doesnt_present),
    ]
