# Generated by Django 3.1.3 on 2020-12-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0004_remove_qrcode_related_value"),
        ("tickets", "0014_auto_20201207_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="qrcodes.qrcode"
            ),
        ),
    ]
