# Generated by Django 3.1.3 on 2020-12-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_auto_20201207_1127"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="promo_code",),
    ]
