# Generated by Django 3.1.3 on 2020-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_guestinvite"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="date_discount",),
        migrations.DeleteModel(name="TicketDiscountByDate",),
    ]
