# Generated by Django 3.1.3 on 2020-12-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0018_auto_20201216_0807"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="selfie_required",
            field=models.BooleanField(default=False),
        ),
    ]
