# Generated by Django 3.1.3 on 2020-12-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0019_ticketcategory_selfie_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSelfie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="ticket-selfies/%Y/%m/%d")),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selfies",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
