# Generated by Django 3.1.3 on 2020-12-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0020_ticketselfie"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketselfie",
            name="telegram_image_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
