# Generated by Django 3.1.3 on 2020-12-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_ticketselfie_telegram_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
