# Generated by Django 3.1.3 on 2020-12-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0023_ticketselfie_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketselfie", options={"ordering": ("-created_at",)},
        ),
    ]
