# Generated by Django 3.1.3 on 2021-01-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0025_auto_20210111_0759"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketcategory", name="payment_confirmation_text",
        ),
    ]
