# Generated by Django 3.1.3 on 2021-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0027_ticket_guest_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketselfie",
            name="admin_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
