# Generated by Django 3.1.3 on 2021-01-27 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qrcodes", "0006_auto_20210127_0720"),
        ("locations", "0008_auto_20201216_0638"),
        ("bots", "0005_auto_20201201_1434"),
        ("tickets", "0028_ticketselfie_admin_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnifiedPass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bots.bot"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.location",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"role": "organizer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="qrcodes.qrcode"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
