# Generated by Django 3.1.3 on 2021-02-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0032_selfiemessage_selfieupload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selfieupload", old_name="image", new_name="file",
        ),
    ]
