# Generated by Django 3.1.3 on 2021-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0033_auto_20210201_1423"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
