# Generated by Django 3.1.3 on 2021-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0036_auto_20210208_2049"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("yoomoney", "YooMoney"), ("fondy", "Fondy")],
                default="",
                max_length=100,
            ),
        ),
    ]
