# Generated by Django 3.1.3 on 2021-02-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0037_ticket_payment_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="ticket", name="payment_type",),
    ]
