# Generated by Django 3.1.3 on 2021-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0038_remove_ticket_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="avoid_selfie_reconfirmation",
            field=models.BooleanField(default=False),
        ),
    ]
