# Generated by Django 3.1.3 on 2021-03-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0039_ticketcategory_avoid_selfie_reconfirmation"),
    ]

    operations = [
        migrations.AlterModelOptions(name="ticket", options={"ordering": ("-id",)},),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("payed", "Действителен"),
                    ("used", "Проход осуществлён"),
                    ("returned", "Выполнен возврат"),
                ],
                default="created",
                max_length=100,
            ),
        ),
    ]
