# Generated by Django 3.1.3 on 2021-03-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0040_auto_20210316_2248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("pending", "Ожидает оплаты"),
                    ("payed", "Действителен"),
                    ("used", "Проход осуществлён"),
                    ("returned", "Выполнен возврат"),
                ],
                default="created",
                max_length=100,
            ),
        ),
    ]
