# Generated by Django 3.1.3 on 2021-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0041_auto_20210318_0036"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcategory",
            name="additional_data_short_request",
            field=models.BooleanField(default=False),
        ),
    ]
