# Generated by Django 3.1.3 on 2020-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Суперадмин"),
                    ("location_owner", "Владелец локации"),
                    ("organizer", "Организатор"),
                ],
                default="super_admin",
                max_length=100,
            ),
        ),
    ]
