# Generated by Django 3.1.3 on 2021-01-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0005_auto_20201201_1434"),
        ("management", "0003_auto_20201119_2133"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminaccount",
            name="notification_bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bots.bot",
            ),
        ),
        migrations.AddField(
            model_name="adminaccount",
            name="telegram_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
