# Generated by Django 3.1.3 on 2021-02-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_adminaccount_organizer_telegram_checkout_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminaccount",
            name="organizer_shop_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="adminaccount",
            name="organizer_shop_secret",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
