# Generated by Django 3.1.3 on 2021-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0006_auto_20210208_2002"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminaccount",
            name="organizer_fondy_merchant_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminaccount",
            name="organizer_fondy_merchant_password",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
