# Generated by Django 3.1.3 on 2020-11-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0002_auto_20201123_1058"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="registered_webhook",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="bot",
            name="secret",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
