# Generated by Django 3.1.3 on 2020-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_auto_20201126_2112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="secret",
            field=models.CharField(
                blank=True, default="", max_length=1000, unique=True
            ),
        ),
    ]
