# Generated by Django 3.1.3 on 2020-12-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_auto_20201128_1803"),
    ]

    operations = [
        migrations.RenameField(model_name="bot", old_name="name", new_name="username",),
    ]
