# Generated by Django 3.1.3 on 2020-11-29 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_auto_20201128_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participantcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="participants.participantcategory",
            ),
        ),
    ]
