# Generated by Django 3.1.3 on 2020-11-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_auto_20201129_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="participant",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="participant",
            name="username",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
