# Generated by Django 3.1.3 on 2020-11-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_auto_20201129_2247"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participant", old_name="category", new_name="staff_category",
        ),
        migrations.RemoveField(model_name="participantcategory", name="role",),
    ]
