# Generated by Django 3.1.3 on 2020-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_auto_20201129_2253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="telegram_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
