# Generated by Django 3.1.3 on 2020-12-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_auto_20201203_0536"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcategory",
            name="is_access_control",
            field=models.BooleanField(default=False),
        ),
    ]
