# Generated by Django 3.1.3 on 2020-12-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0010_auto_20201204_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffcategory",
            name="stereotype",
            field=models.CharField(
                blank=True,
                choices=[("access_control", "Пропускной контроль")],
                max_length=500,
                null=True,
            ),
        ),
    ]
