# Generated by Django 3.1.3 on 2020-12-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_auto_20201208_1123"),
        ("participants", "0012_auto_20201208_1123"),
        ("events", "0014_auto_20201208_1123"),
    ]

    operations = [
        migrations.DeleteModel(name="StaffCategory",),
    ]
