# Generated by Django 3.1.3 on 2021-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0013_delete_staffcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
