# Generated by Django 3.1.3 on 2021-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0014_participant_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=9
            ),
        ),
    ]
