# Generated by Django 3.1.3 on 2021-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0015_participant_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="telegram_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
