# Generated by Django 3.1.3 on 2020-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0002_auto_20201205_0626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="type",
            field=models.CharField(
                choices=[
                    ("ticket", "Билет"),
                    ("staff", "Персонал"),
                    ("staff_invite", "Инвайт для персонала"),
                    ("promo", "Промо-код"),
                ],
                max_length=100,
            ),
        ),
    ]
