# Generated by Django 3.1.3 on 2020-12-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0004_remove_qrcode_related_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="type",
            field=models.CharField(
                choices=[
                    ("ticket", "Билет"),
                    ("staff", "Персонал"),
                    ("staff_invite", "Инвайт для персонала"),
                    ("guest_invite", "Инвайт для гостей"),
                ],
                max_length=100,
            ),
        ),
    ]
