# Generated by Django 3.1.3 on 2021-01-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodes", "0005_auto_20201216_0807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="type",
            field=models.CharField(
                choices=[
                    ("ticket", "Билет"),
                    ("staff", "Персонал"),
                    ("staff_invite", "Инвайт для персонала"),
                    ("guest_invite", "Инвайт для гостей"),
                    ("unified_pass", "Универсальный пропуск"),
                ],
                max_length=100,
            ),
        ),
    ]
