# Generated by Django 3.1.3 on 2020-11-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_auto_20201122_0746"),
    ]

    operations = [
        migrations.RenameField(
            model_name="broadcastnotification",
            old_name="participant_category",
            new_name="staff_category",
        ),
    ]
