# Generated by Django 3.1.3 on 2020-12-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("notifications", "0003_auto_20201129_2307"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastnotification",
            name="staff_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staff.staffcategory"
            ),
        ),
    ]
