# Generated by Django 3.1.3 on 2020-12-20 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_selfie_rejected_text"),
        ("tickets", "0024_auto_20201217_1525"),
        ("staff", "0013_auto_20201213_1457"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0005_auto_20201219_1635"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BroadcastNotification", new_name="Notification",
        ),
    ]
