# Generated by Django 3.1.3 on 2020-12-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0021_event_selfie_rejected_text"),
        ("notifications", "0008_auto_20201221_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.event",
            ),
        ),
    ]
