# Generated by Django 3.1.3 on 2020-12-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_auto_20201216_0638"),
        ("notifications", "0009_auto_20201223_1925"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.location",
            ),
        ),
    ]
