# Generated by Django 3.1.3 on 2021-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_notification_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("to_all", "Всем"),
                    ("to_staff", "Персоналу"),
                    ("to_guests", "Гостям"),
                ],
                max_length=100,
            ),
        ),
    ]
