# Generated by Django 3.1.3 on 2021-02-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileuploads", "0004_auto_20210221_0748"),
        ("notifications", "0011_auto_20210111_0759"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fileuploads.imageupload",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="telegram_poster_id",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
