# Generated by Django 3.1.3 on 2021-05-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_auto_20210222_0539"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification", options={"ordering": ("-id",)},
        ),
    ]
